Repository FRONTENDBOOTCAMP-12th/1Piece, pull requests merged in 2025-03, with the labels that each got.

#8 [MERGE] : vercel 배포 과정 중 오류 수정
  vite.config.ts
Labels: Chore

#33 [MERGE] : 선지 컴포넌트 develop 브랜치로 병합
  src/components/Option/Option.module.css
  src/components/Option/Option.tsx
Labels: Feature

#45 [FEAT] : 프로그레스 섹션 구현
  src/components/ProgressBar/ProgressBar.module.css
  src/components/ProgressBar/ProgressBar.tsx
Labels: Feature

#46 [MERGE] : components/question 병합
  src/components/Question/Question.module.css
  src/components/Question/Question.tsx
Labels: Feature

#47 [MERGE] : radio-question 제작
  src/components/Input/Input.tsx
  src/components/RadioQuestion/RadioQuestion.module.css
  src/components/RadioQuestion/RadioQuestion.tsx
Labels: Fix, Feature, Modify

#54 [FEAT] : 댓글 컴포넌트 제작
  src/components/Comment/Comment.module.css
  src/components/Comment/Comment.tsx
Labels: Feature

#67 [FEAT] : 책갈피 컴포넌트 제작
  src/components/MyPageTab/MyPageTab.module.css
  src/components/MyPageTab/MyPageTab.tsx
Labels: Feature

#82 [FEAT] : 문제 풀이 결과 컴포넌트 제작
  public/images/solved_message.svg
  src/components/QuizResult/QuizResult.module.css
  src/components/QuizResult/QuizResult.tsx
Labels: Feature

#120 [FEAT] : 댓글 목록 컴포넌트 제작
  src/components/Comment/Comment.module.css
  src/components/CommentList/CommentList.module.css
  src/components/CommentList/CommentList.tsx
Labels: Feature, Design

#122 [FEAT] : 문제 풀이 완료 페이지 컴포넌트 배치
  src/App.tsx
  src/pages/ProblemSolved/Page.module.css
  src/pages/ProblemSolved/Page.tsx
Labels: Feature, Chore

#162 [FEAT] : 문제 풀이 완료 페이지 기능 구현
  src/components/Card/BookMark.tsx
  src/pages/QuizComplete/Page.tsx
Labels: Feature, Page

#184 [FEAT] : 북마크 상태 관리
  src/components/Card/BookMark.tsx
  src/components/Card/Card.tsx
  src/lib/BookmarkState.tsx
  src/pages/LogIn/Page.tsx
  src/pages/QuizComplete/Page.tsx
  src/pages/QuizComplete/components/InputBox.tsx
Labels: Feature

#228 [MERGE] : 문제 풀이 완료 페이지 오작동 수정 및 에러 해결
  src/components/Comment/Comment.tsx
  src/components/CommentList/CommentList.tsx
  src/pages/QuizComplete/Page.tsx
  src/pages/QuizComplete/components/InputBox.tsx
Labels: Fix, Modify

#265 [MERGE] : 문제 풀이 완료 페이지 폭죽 추가
  package.json
  pnpm-lock.yaml
  src/components/QuizResult/QuizResult.module.css
  src/components/QuizResult/QuizResult.tsx
  src/pages/QuizComplete/Page.tsx
Labels: Feature, Merge, Build

#268 [MERGE] : 문제 풀이 완료 페이지 CSS 수정
  src/pages/QuizComplete/Page.module.css
  src/pages/QuizComplete/components/InputBox.module.css
Labels: Design

#275 [MERGE] : 댓글 삭제 기능 추가 및 병합
  src/components/Comment/Comment.module.css
  src/components/Comment/Comment.tsx
  src/components/CommentList/CommentList.tsx
  src/pages/QuizComplete/Page.tsx
Labels: Feature

#291 [MERGE] : CSS 수정 및 병합
  src/components/QuizResult/QuizResult.module.css
  src/pages/QuizComplete/components/InputBox.module.css
Labels: Design
